<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'PhpParser\\' => array($vendorDir . '/nikic/php-parser/lib/PhpParser'),
    'DeepCopy\\' => array($vendorDir . '/myclabs/deep-copy/src/DeepCopy'),
    'DRPPSM\\Traits\\' => array($baseDir . '/src/Core/Traits'),
    'DRPPSM\\Tests\\' => array($baseDir . '/tests/unit'),
    'DRPPSM\\Logging\\' => array($baseDir . '/src/Core/Logging'),
    'DRPPSM\\Interfaces\\' => array($baseDir . '/src/Core/Interfaces'),
    'DRPPSM\\Exceptions\\' => array($baseDir . '/src/Core/Exceptions'),
    'DRPPSM\\Constants\\' => array($baseDir . '/src/Core/Constants'),
    'DRPPSM\\Abstracts\\' => array($baseDir . '/src/Core/Abstracts'),
    'DRPPSM\\' => array($baseDir . '/src'),
);
