<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit672fe16c65cc53aa8b66e730cdfce0de
{
    public static $files = array (
        '1df5f1ca3d8a01ce642e3b1a54844504' => __DIR__ . '/../..' . '/src/Core/Functions/facades.php',
        '2b1771712136d63f0ed4fa70e62557eb' => __DIR__ . '/../..' . '/src/Core/Functions/core.php',
        '0ecdf14f9753bb884fe2a3c55c79a401' => __DIR__ . '/../..' . '/src/Core/Functions/defines.php',
        'd75c4dd93ef9af06b15ee96390970d1c' => __DIR__ . '/../..' . '/src/Core/Functions/misc.php',
        '508f928bcc69d4d7257b594ca5e3ed26' => __DIR__ . '/../..' . '/src/Core/Functions/include.php',
        '18ce892445e99103f067dd10d355c2b0' => __DIR__ . '/../..' . '/src/Core/Functions/interfaces.php',
        '1bf42cb946e1f36ab7e284ac9bd55dd2' => __DIR__ . '/../..' . '/src/Core/Functions/database.php',
        '8e0760fd21128b00441ec5c4abbdfb75' => __DIR__ . '/../..' . '/src/Core/Functions/templates.php',
    );

    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DRPPSM\\Traits\\' => 14,
            'DRPPSM\\Tests\\' => 13,
            'DRPPSM\\Logging\\' => 15,
            'DRPPSM\\Interfaces\\' => 18,
            'DRPPSM\\Exceptions\\' => 18,
            'DRPPSM\\Constants\\' => 17,
            'DRPPSM\\Abstracts\\' => 17,
            'DRPPSM\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DRPPSM\\Traits\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/Core/Traits',
        ),
        'DRPPSM\\Tests\\' => 
        array (
            0 => __DIR__ . '/../..' . '/tests',
        ),
        'DRPPSM\\Logging\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/Core/Logging',
        ),
        'DRPPSM\\Interfaces\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/Core/Interfaces',
        ),
        'DRPPSM\\Exceptions\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/Core/Exceptions',
        ),
        'DRPPSM\\Constants\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/Core/Constants',
        ),
        'DRPPSM\\Abstracts\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/Core/Abstracts',
        ),
        'DRPPSM\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'DRPPSM\\AdminMenu' => __DIR__ . '/../..' . '/src/AdminMenu.php',
        'DRPPSM\\AdminSettings' => __DIR__ . '/../..' . '/src/AdminSettings.php',
        'DRPPSM\\App' => __DIR__ . '/../..' . '/src/App.php',
        'DRPPSM\\BibleLoader' => __DIR__ . '/../..' . '/src/BibleLoader.php',
        'DRPPSM\\Constants\\Actions' => __DIR__ . '/../..' . '/src/Core/Constants/Actions.php',
        'DRPPSM\\Constants\\Bible' => __DIR__ . '/../..' . '/src/Core/Constants/Bible.php',
        'DRPPSM\\Constants\\Caps' => __DIR__ . '/../..' . '/src/Core/Constants/Caps.php',
        'DRPPSM\\Constants\\Meta' => __DIR__ . '/../..' . '/src/Core/Constants/Meta.php',
        'DRPPSM\\Container' => __DIR__ . '/../..' . '/src/Container.php',
        'DRPPSM\\DB\\DbUpdates' => __DIR__ . '/../..' . '/src/DB/DbUpdates.php',
        'DRPPSM\\DB\\M001M000P000' => __DIR__ . '/../..' . '/src/DB/M001M000P000.php',
        'DRPPSM\\DateUtils' => __DIR__ . '/../..' . '/src/DateUtils.php',
        'DRPPSM\\Deactivator' => __DIR__ . '/../..' . '/src/Deactivator.php',
        'DRPPSM\\Exceptions\\NotfoundException' => __DIR__ . '/../..' . '/src/Core/Exceptions/NotfoundException.php',
        'DRPPSM\\Exceptions\\PluginException' => __DIR__ . '/../..' . '/src/Core/Exceptions/PluginException.php',
        'DRPPSM\\FatalError' => __DIR__ . '/../..' . '/src/FatalError.php',
        'DRPPSM\\Helper' => __DIR__ . '/../..' . '/src/Helper.php',
        'DRPPSM\\HooksUtils' => __DIR__ . '/../..' . '/src/HooksUtils.php',
        'DRPPSM\\ImageSize' => __DIR__ . '/../..' . '/src/ImageSize.php',
        'DRPPSM\\Interfaces\\AdminMenuInt' => __DIR__ . '/../..' . '/src/Core/Interfaces/AdminMenuInt.php',
        'DRPPSM\\Interfaces\\BaseInt' => __DIR__ . '/../..' . '/src/Core/Interfaces/BaseInt.php',
        'DRPPSM\\Interfaces\\BibleLoaderInt' => __DIR__ . '/../..' . '/src/Core/Interfaces/BibleLoaderInt.php',
        'DRPPSM\\Interfaces\\ContainerInt' => __DIR__ . '/../..' . '/src/Core/Interfaces/ContainerInt.php',
        'DRPPSM\\Interfaces\\DbInt' => __DIR__ . '/../..' . '/src/Core/Interfaces/DbInt.php',
        'DRPPSM\\Interfaces\\Executable' => __DIR__ . '/../..' . '/src/Core/Interfaces/Executable.php',
        'DRPPSM\\Interfaces\\Initable' => __DIR__ . '/../..' . '/src/Core/Interfaces/Initable.php',
        'DRPPSM\\Interfaces\\NoticeInt' => __DIR__ . '/../..' . '/src/Core/Interfaces/NoticeInt.php',
        'DRPPSM\\Interfaces\\OptionsInt' => __DIR__ . '/../..' . '/src/Core/Interfaces/OptionsInt.php',
        'DRPPSM\\Interfaces\\PermaLinkInt' => __DIR__ . '/../..' . '/src/Core/Interfaces/PermaLinkInt.php',
        'DRPPSM\\Interfaces\\PluginInt' => __DIR__ . '/../..' . '/src/Core/Interfaces/PluginInt.php',
        'DRPPSM\\Interfaces\\Registrable' => __DIR__ . '/../..' . '/src/Core/Interfaces/Registrable.php',
        'DRPPSM\\Interfaces\\RequirementsInt' => __DIR__ . '/../..' . '/src/Core/Interfaces/RequirementsInt.php',
        'DRPPSM\\Interfaces\\RolesInt' => __DIR__ . '/../..' . '/src/Core/Interfaces/RolesInt.php',
        'DRPPSM\\Interfaces\\Runable' => __DIR__ . '/../..' . '/src/Core/Interfaces/Runable.php',
        'DRPPSM\\Interfaces\\TextDomainInt' => __DIR__ . '/../..' . '/src/Core/Interfaces/TextDomainInt.php',
        'DRPPSM\\Loader' => __DIR__ . '/../..' . '/src/Loader.php',
        'DRPPSM\\Logger' => __DIR__ . '/../..' . '/src/Logger.php',
        'DRPPSM\\Logging\\LogDatabase' => __DIR__ . '/../..' . '/src/Core/Logging/LogDatabase.php',
        'DRPPSM\\Logging\\LogFile' => __DIR__ . '/../..' . '/src/Core/Logging/LogFile.php',
        'DRPPSM\\Logging\\LogRecord' => __DIR__ . '/../..' . '/src/Core/Logging/LogRecord.php',
        'DRPPSM\\Logging\\LogWritterAbs' => __DIR__ . '/../..' . '/src/Core/Logging/LogWritterAbs.php',
        'DRPPSM\\Logging\\LogWritterInt' => __DIR__ . '/../..' . '/src/Core/Logging/LogWritterInt.php',
        'DRPPSM\\Logging\\LoggerInt' => __DIR__ . '/../..' . '/src/Core/Logging/LoggerInt.php',
        'DRPPSM\\Notice' => __DIR__ . '/../..' . '/src/Notice.php',
        'DRPPSM\\Options' => __DIR__ . '/../..' . '/src/Options.php',
        'DRPPSM\\PermaLinks' => __DIR__ . '/../..' . '/src/PermaLinks.php',
        'DRPPSM\\Plugin' => __DIR__ . '/../..' . '/src/Plugin.php',
        'DRPPSM\\PostTypeReg' => __DIR__ . '/../..' . '/src/PostTypeReg.php',
        'DRPPSM\\PostTypeSetup' => __DIR__ . '/../..' . '/src/PostTypeSetup.php',
        'DRPPSM\\PostTypeUtils' => __DIR__ . '/../..' . '/src/PostTypeUtils.php',
        'DRPPSM\\QueryVars' => __DIR__ . '/../..' . '/src/QueryVars.php',
        'DRPPSM\\QueueScripts' => __DIR__ . '/../..' . '/src/QueueScripts.php',
        'DRPPSM\\Requirements' => __DIR__ . '/../..' . '/src/Requirements.php',
        'DRPPSM\\Rewrite' => __DIR__ . '/../..' . '/src/Rewrite.php',
        'DRPPSM\\Roles' => __DIR__ . '/../..' . '/src/Roles.php',
        'DRPPSM\\SCBase' => __DIR__ . '/../..' . '/src/SCBase.php',
        'DRPPSM\\SCSeriesLatest' => __DIR__ . '/../..' . '/src/SCSeriesLatest.php',
        'DRPPSM\\SCSermonImages' => __DIR__ . '/../..' . '/src/SCSermonImages.php',
        'DRPPSM\\SCSermonLatest' => __DIR__ . '/../..' . '/src/SCSermonLatest.php',
        'DRPPSM\\SCSermonSorting' => __DIR__ . '/../..' . '/src/SCSermonSorting.php',
        'DRPPSM\\SCSermons' => __DIR__ . '/../..' . '/src/SCSermons.php',
        'DRPPSM\\SCTerms' => __DIR__ . '/../..' . '/src/SCTerms.php',
        'DRPPSM\\SermonComments' => __DIR__ . '/../..' . '/src/SermonComments.php',
        'DRPPSM\\SermonDetail' => __DIR__ . '/../..' . '/src/SermonDetail.php',
        'DRPPSM\\SermonEdit' => __DIR__ . '/../..' . '/src/SermonEdit.php',
        'DRPPSM\\SermonFiles' => __DIR__ . '/../..' . '/src/SermonFiles.php',
        'DRPPSM\\SermonImageAttach' => __DIR__ . '/../..' . '/src/SermonImageAttach.php',
        'DRPPSM\\SermonListTable' => __DIR__ . '/../..' . '/src/SermonListTable.php',
        'DRPPSM\\SermonSorting' => __DIR__ . '/../..' . '/src/SermonSorting.php',
        'DRPPSM\\Settings' => __DIR__ . '/../..' . '/src/Settings.php',
        'DRPPSM\\SettingsAdvanced' => __DIR__ . '/../..' . '/src/SettingsAdvanced.php',
        'DRPPSM\\SettingsBase' => __DIR__ . '/../..' . '/src/SettingsBase.php',
        'DRPPSM\\SettingsDisplay' => __DIR__ . '/../..' . '/src/SettingsDisplay.php',
        'DRPPSM\\SettingsGeneral' => __DIR__ . '/../..' . '/src/SettingsGeneral.php',
        'DRPPSM\\TaxUtils' => __DIR__ . '/../..' . '/src/TaxUtils.php',
        'DRPPSM\\TaxonomyImageAttach' => __DIR__ . '/../..' . '/src/TaxonomyImageAttach.php',
        'DRPPSM\\TaxonomyListTable' => __DIR__ . '/../..' . '/src/TaxonomyListTable.php',
        'DRPPSM\\TaxonomyReg' => __DIR__ . '/../..' . '/src/TaxonomyReg.php',
        'DRPPSM\\Templates' => __DIR__ . '/../..' . '/src/Templates.php',
        'DRPPSM\\Tests\\AdminSermonTest' => __DIR__ . '/../..' . '/tests/AdminSermonTest.php',
        'DRPPSM\\Tests\\AppTest' => __DIR__ . '/../..' . '/tests/AppTest.php',
        'DRPPSM\\Tests\\BaseTest' => __DIR__ . '/../..' . '/tests/BaseTest.php',
        'DRPPSM\\Tests\\ContainerTest' => __DIR__ . '/../..' . '/tests/ContainerTest.php',
        'DRPPSM\\Tests\\FatalErrorTest' => __DIR__ . '/../..' . '/tests/FatalErrorTest.php',
        'DRPPSM\\Tests\\HelperTest' => __DIR__ . '/../..' . '/tests/HelperTest.php',
        'DRPPSM\\Tests\\HooksUtilsTest' => __DIR__ . '/../..' . '/tests/HooksUtilsTest.php',
        'DRPPSM\\Tests\\ImageSizeTest' => __DIR__ . '/../..' . '/tests/ImageSizeTest.php',
        'DRPPSM\\Tests\\LoggerTest' => __DIR__ . '/../..' . '/tests/LoggerTest.php',
        'DRPPSM\\Tests\\NoticeTest' => __DIR__ . '/../..' . '/tests/NoticeTest.php',
        'DRPPSM\\Tests\\OptionsTest' => __DIR__ . '/../..' . '/tests/OptionsTest.php',
        'DRPPSM\\Tests\\PermaLinkTest' => __DIR__ . '/../..' . '/tests/PermaLinkTest.php',
        'DRPPSM\\Tests\\PluginTest' => __DIR__ . '/../..' . '/tests/PluginTest.php',
        'DRPPSM\\Tests\\PostTypeSetupTest' => __DIR__ . '/../..' . '/tests/PostTypeSetupTest.php',
        'DRPPSM\\Tests\\QueryVarsTest' => __DIR__ . '/../..' . '/tests/QueryVarsTest.php',
        'DRPPSM\\Tests\\RequirementsTest' => __DIR__ . '/../..' . '/tests/RequirementsTest.php',
        'DRPPSM\\Tests\\RolesTest' => __DIR__ . '/../..' . '/tests/RolesTest.php',
        'DRPPSM\\Tests\\SermonCommentsTest' => __DIR__ . '/../..' . '/tests/SermonCommentsTest.php',
        'DRPPSM\\Tests\\SermonDetailTest' => __DIR__ . '/../..' . '/tests/SermonDetailTest.php',
        'DRPPSM\\Tests\\SermonFilesTest' => __DIR__ . '/../..' . '/tests/SermonFilesTest.php',
        'DRPPSM\\Tests\\TaxUtilsTest' => __DIR__ . '/../..' . '/tests/TaxUtilsTest.php',
        'DRPPSM\\Tests\\TaxonomyRegTest' => __DIR__ . '/../..' . '/tests/TaxonomyRegTest.php',
        'DRPPSM\\Tests\\TextDomainTest' => __DIR__ . '/../..' . '/tests/TextDomainTest.php',
        'DRPPSM\\TextDomain' => __DIR__ . '/../..' . '/src/TextDomain.php',
        'DRPPSM\\Timer' => __DIR__ . '/../..' . '/src/Timer.php',
        'DRPPSM\\Traits\\OverLoadTrait' => __DIR__ . '/../..' . '/src/Core/Traits/OverLoadTrait.php',
        'DRPPSM\\Traits\\SingletonTrait' => __DIR__ . '/../..' . '/src/Core/Traits/SingletonTrait.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit672fe16c65cc53aa8b66e730cdfce0de::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit672fe16c65cc53aa8b66e730cdfce0de::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit672fe16c65cc53aa8b66e730cdfce0de::$classMap;

        }, null, ClassLoader::class);
    }
}
